server:
  port: 8762

eureka:
  instance:
    hostname: localhost # 注册中心的主机名
  client:
    register-with-eureka: false # false让注册中心不要注册自己
    fetch-registry: false # 表示不去服务端检索其他服务信息，注册中心的职责是维护服务实例
    service-url:
      defaultZone: http://eureka8763:8763/eureka,http://eureka8764:8764/eureka # 指定注册中心的地址