server:
  port: 8081

spring:
  application:
    name: spring-cloud-goods

management:
  endpoints:
    web:
      exposure: *  # 打开所有的Web访问端点

eureka:
  instance:
    lease-renewal-interval-in-seconds: 2 # 客户端每2s发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10s 没有发送心跳说明客户端故障，服务会被踢出去
    prefer-ip-address: true # true说明客户端服务的服务实例以IP作为链接，而不是域名
    instance-id: spring-cloud-goods-8081 # 告诉注册中心服务实例的id，id是唯一的
  client:
    service-url:
      defaultZone: http://eureka8762:8762/eureka,http://eureka8763:8763/eureka,http://eureka8764:8764/eureka # 注册中心的连接地址